### ISSUE TITLE
Implementing todo lists

### ISSUE THREAD

**Issue by A-Romann** [otto001/teha#2]
- [ ] Allow the user to toggle between different todo visualizations: todos of a day, a
week, and other lists (todos of a specific project).
- [ ] Add lists of all todos, completed todos, and reoccurring todos
- [ ] Visualize the todos of each list appropriately.
- [ ] Your todo view should support showing current and completed todos.
- [ ] Offer an option to display more details on each todo.
